<?php
/**
 * Services overview page.
 *
 * @package the-ebook-edit
 */

get_header();
?>

<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a> / Services</div><p class="eyebrow">Services</p><h1>Editorial support from idea to publication.</h1><p class="lead">Build a complete ebook or strengthen one specific stage with writing, editing, formatting, and publishing services tailored to your manuscript.</p></div></section>
<section class="section"><div class="container grid-2">
  <article class="card card-accent reveal"><div class="icon-tile">W</div><h2>Ebook writing</h2><p>Transform expertise, interviews, notes, recordings, or a rough draft into a coherent manuscript that sounds natural and purposeful.</p><ul class="service-list"><li>Concept and audience positioning</li><li>Book promise and chapter outline</li><li>Research planning and source organization</li><li>Ghostwriting or collaborative writing</li><li>Revision based on structured feedback</li></ul><a class="button button-outline" href="<?php echo esc_url( home_url( '/writing/' ) ); ?>">View writing services</a></article>
  <article class="card card-accent reveal"><div class="icon-tile">E</div><h2>Editing</h2><p>Choose the editing level that matches the manuscript’s needs, from big-picture structure to final proofreading.</p><ul class="service-list"><li>Editorial assessment</li><li>Developmental editing</li><li>Line and copy editing</li><li>Proofreading</li><li>Style sheet and consistency checks</li></ul><a class="button button-outline" href="<?php echo esc_url( home_url( '/editing/' ) ); ?>">View editing services</a></article>
  <article class="card card-accent reveal"><div class="icon-tile">F</div><h2>Formatting and conversion</h2><p>Prepare an attractive, readable, and technically clean ebook interior for common digital reading environments.</p><ul class="service-list"><li>EPUB preparation</li><li>PDF layout</li><li>Clickable table of contents</li><li>Front and back matter setup</li><li>Device and file quality checks</li></ul><a class="button button-outline" href="<?php echo esc_url( home_url( '/publishing/' ) ); ?>#formatting">View formatting support</a></article>
  <article class="card card-accent reveal"><div class="icon-tile">P</div><h2>Publishing support</h2><p>Move from final files to a clear publication plan with practical guidance around metadata, platforms such as Amazon KDP, Apple Books, Kobo, Google Play Books, and Barnes &amp; Noble Press, and launch materials.</p><ul class="service-list"><li>Publishing route planning</li><li>Book description and metadata support</li><li>Upload checklist and file organization</li><li>Quality assurance before launch</li><li>Post-publication update plan</li></ul><a class="button button-outline" href="<?php echo esc_url( home_url( '/publishing/' ) ); ?>">View Kindle &amp; ebook publishing support</a></article>
</div></section>
<section class="section section-blue"><div class="container split"><div><p class="eyebrow">Not sure what you need?</p><h2>Begin with an editorial assessment.</h2><p class="lead">We review the manuscript’s structure, clarity, consistency, readiness, and likely next steps before recommending a scope.</p></div><div><ul class="mini-list"><li><span class="tick">✓</span><span>Current strengths and risks</span></li><li><span class="tick">✓</span><span>Recommended editing level</span></li><li><span class="tick">✓</span><span>Priority improvements</span></li><li><span class="tick">✓</span><span>Suggested production sequence</span></li></ul><a class="button button-gold" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Request an assessment</a></div></div></section>
<section class="section"><div class="container"><p class="eyebrow">Common combinations</p><h2>Services can be combined without overcomplicating the project.</h2><div class="grid-3 cards"><article class="card"><h3>Draft to polished manuscript</h3><p>Developmental edit → author revision → copy edit → proofread.</p></article><article class="card"><h3>Idea to complete ebook</h3><p>Strategy → outline → collaborative writing → full editorial workflow.</p></article><article class="card"><h3>Manuscript to market</h3><p>Final edit → formatting → metadata → upload and launch checklist.</p></article></div></div></section>
<section class="section-tight"><div class="container"><div class="cta-band"><h2>Get a scope built around the actual manuscript.</h2><p>Share the current draft, approximate length, desired services, and target date. No generic package should replace a careful review of the work.</p><a class="button button-gold" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Tell us about your project</a></div></div></section>

<?php
get_footer();
