<?php
/**
 * Ebook writing service page.
 *
 * @package the-ebook-edit
 */

get_header();
?>

<section class="page-hero"><div class="container"><p class="eyebrow">Ebook writing</p><h1>Turn expertise, experience, or a rough idea into a book readers can follow.</h1><p class="lead">Develop a clear concept, useful structure, and engaging manuscript through ghostwriting or a collaborative author partnership.</p></div></section>
<section class="section"><div class="container split"><div><p class="eyebrow">What we can build from</p><h2>You do not need a perfect first draft.</h2><p>Projects can begin with a concept, workshop, course, podcast series, research notes, voice recordings, interviews, presentations, or an incomplete manuscript.</p><div class="pill-row"><span class="pill">Expertise</span><span class="pill">Interview notes</span><span class="pill">Course material</span><span class="pill">Rough draft</span><span class="pill">Recorded ideas</span></div></div><div class="feature-panel reveal"><h3>A strong writing engagement includes</h3><ul class="mini-list"><li><span class="tick">✓</span><span>A clear reader and outcome</span></li><li><span class="tick">✓</span><span>A chapter-by-chapter logic</span></li><li><span class="tick">✓</span><span>Agreed voice and tone examples</span></li><li><span class="tick">✓</span><span>Regular review milestones</span></li><li><span class="tick">✓</span><span>Documented decisions and revisions</span></li></ul></div></div></section>
<section class="section section-soft"><div class="container"><p class="eyebrow">Writing options</p><h2>Choose the collaboration model that fits your time and voice.</h2><div class="grid-3 cards"><article class="card"><div class="icon-tile">01</div><h3>Ghostwriting</h3><p>You provide subject matter, interviews, source material, and feedback. We develop the manuscript in an agreed voice.</p></article><article class="card"><div class="icon-tile">02</div><h3>Collaborative writing</h3><p>We build the structure together, then alternate drafting and revision responsibilities around your strengths.</p></article><article class="card"><div class="icon-tile">03</div><h3>Book development</h3><p>You write the draft while receiving outline support, chapter feedback, accountability, and editorial direction.</p></article></div></div></section>
<section class="section"><div class="container"><p class="eyebrow">Typical workflow</p><h2>From concept to complete manuscript</h2><div class="steps"><article class="step"><div><h3>Discovery and positioning</h3><p>Define the audience, problem, promise, format, voice, and business or creative purpose.</p></div></article><article class="step"><div><h3>Outline and sample</h3><p>Create a detailed outline and sample section so direction is approved before full drafting.</p></div></article><article class="step"><div><h3>Research and interviews</h3><p>Gather source material, examples, stories, evidence, and original insight in an organized way.</p></div></article><article class="step"><div><h3>Milestone drafting</h3><p>Draft in planned sections, review feedback, and prevent late-stage structural surprises.</p></div></article><article class="step"><div><h3>Revision and editorial handoff</h3><p>Complete author revisions, confirm the manuscript, and move into the editing workflow.</p></div></article></div></div></section>
<section class="section section-gold"><div class="container"><div class="quote-block"><p>A book written in your voice should feel recognizably yours—not like generic marketing copy stretched across chapters.</p><small>The Ebook Edit writing standard</small></div></div></section>
<section class="section-tight"><div class="container"><div class="cta-band"><h2>Bring the idea. We will help build the book around it.</h2><p>Share your subject, audience, available source material, desired length, and target date to begin a writing scope.</p><a class="button button-gold" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Discuss a writing project</a></div></div></section>

<?php
get_footer();
