<?php
/**
 * About — /about/.
 *
 * Ported from the approved design; hand-maintained from here.
 * wordpress/sync-from-static.py does not generate this file.
 *
 * @package the-ebook-edit
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

get_header();
?>

<section class="site-view" id="about-view">
<section class="page-hero "><div class="flow-wrap" aria-hidden="true"><div class="flow-line one"></div><div class="flow-line two"></div></div><div class="container" style="position:relative;z-index:1"><div class="page-hero-grid"><div class="v-reveal"><div class="eyebrow">About The Ebook Edit</div><h1 class="v-h1 about-h1" tabindex="-1">Helping Ideas Become<br>Books Worth Publishing</h1><div class="about-intro"><p class="v-lead">The Ebook Edit helps authors, professionals/experts, coaches/consultants, and entrepreneurs turn their ideas, existing material and manuscripts into a professionally written and published book.</p><p class="v-lead">From writing and editing to formatting, illustration, cover design, publishing and marketing, we can support one stage of a project or guide the journey from concept to publication.</p></div></div><div class="v-reveal" data-delay="1"><div class="about-visual" aria-hidden="true"><img src="<?php echo esc_url( teebe_site_image( 'logo' ) ); ?>" class="av-logo" data-asset="logo" alt=""><div class="av-book av-1"><img src="<?php echo esc_url( teebe_site_image( 'cover-6' ) ); ?>" data-asset="cover-6" alt="The Other Side of Maybe book cover" decoding="async" ></div><div class="av-book av-2"><img src="<?php echo esc_url( teebe_site_image( 'cover-4' ) ); ?>" data-asset="cover-4" alt="The Inner Compass book cover" decoding="async" ></div><div class="av-book av-3"><img src="<?php echo esc_url( teebe_site_image( 'cover-3' ) ); ?>" data-asset="cover-3" alt="The Ghost of Blackthorn Palace book cover" decoding="async" ></div><div class="av-book av-4"><img src="<?php echo esc_url( teebe_site_image( 'cover-5' ) ); ?>" data-asset="cover-5" alt="Rising Through the Storm book cover" decoding="async" ></div></div></div></div></div></section><section class="v-section"><div class="container"><div class="v-head v-reveal"><div><div class="eyebrow">Our approach</div><h2 class="one-line">Three Things We Hold To</h2></div></div><div class="values"><div class="value v-reveal" data-delay="0"><div class="glyph" aria-hidden="true">✦</div><h3>Craft</h3><p>Manuscripts, artwork and files handled with the attention a finished book deserves.</p></div><div class="value v-reveal" data-delay="1"><div class="glyph" aria-hidden="true">❝</div><h3>Clarity</h3><p>Every decision, from a sentence to a cover, should make the book easier to understand and enjoy.</p></div><div class="value v-reveal" data-delay="2"><div class="glyph" aria-hidden="true">❧</div><h3>Collaboration</h3><p>You review and approve at each stage. The book stays yours.</p></div></div></div></section><section class="v-section tight kinds-section"><div class="container"><div class="v-head center v-reveal"><div class="eyebrow">What we help create</div><h2>Books of Every Kind</h2></div>
<div class="kinds-grid">
<a class="kind-card v-reveal" data-delay="0" href="<?php echo esc_url( home_url( '/portfolio/' ) . '#pf-ghost-of-blackthorn-palace' ); ?>"><span class="kind-cover"><img src="<?php echo esc_url( teebe_site_image( 'cover-3' ) ); ?>" data-asset="cover-3" alt="The Ghost of Blackthorn Palace book cover" decoding="async"></span><span class="kind-text"><span class="kind-label">Fiction</span><span class="kind-sub">From our portfolio: The Ghost of Blackthorn Palace</span></span></a>
<a class="kind-card v-reveal" data-delay="1" href="<?php echo esc_url( home_url( '/portfolio/' ) . '#pf-from-the-white-house-to-the-outhouse' ); ?>"><span class="kind-cover"><img src="<?php echo esc_url( teebe_site_image( 'cover-1' ) ); ?>" data-asset="cover-1" alt="From the White House to the Outhouse book cover" decoding="async"></span><span class="kind-text"><span class="kind-label">Non-fiction</span><span class="kind-sub">From our portfolio: From the White House to the Outhouse</span></span></a>
<a class="kind-card v-reveal" data-delay="2" href="<?php echo esc_url( home_url( '/portfolio/' ) . '#pf-rising-through-the-storm' ); ?>"><span class="kind-cover"><img src="<?php echo esc_url( teebe_site_image( 'cover-5' ) ); ?>" data-asset="cover-5" alt="Rising Through the Storm book cover" decoding="async"></span><span class="kind-text"><span class="kind-label">Memoirs</span><span class="kind-sub">From our portfolio: Rising Through the Storm</span></span></a>
<a class="kind-card v-reveal" data-delay="0" href="<?php echo esc_url( home_url( '/portfolio/' ) . '#pf-the-inner-compass' ); ?>"><span class="kind-cover"><img src="<?php echo esc_url( teebe_site_image( 'cover-4' ) ); ?>" data-asset="cover-4" alt="The Inner Compass book cover" decoding="async"></span><span class="kind-text"><span class="kind-label">Business Books</span><span class="kind-sub">From our portfolio: The Inner Compass</span></span></a>
<a class="kind-card v-reveal" data-delay="1" href="<?php echo esc_url( home_url( '/portfolio/' ) . '#pf-the-inner-compass' ); ?>"><span class="kind-cover"><img src="<?php echo esc_url( teebe_site_image( 'cover-4' ) ); ?>" data-asset="cover-4" alt="The Inner Compass book cover" decoding="async"></span><span class="kind-text"><span class="kind-label">Personal Development</span><span class="kind-sub">From our portfolio: The Inner Compass</span></span></a>
<a class="kind-card v-reveal" data-delay="2" href="<?php echo esc_url( home_url( '/portfolio/' ) . '#pf-mila-and-the-gentle-dino' ); ?>"><span class="kind-cover"><img src="<?php echo esc_url( teebe_site_image( 'cover-2' ) ); ?>" data-asset="cover-2" alt="Mila and the Gentle Dino book cover" decoding="async"></span><span class="kind-text"><span class="kind-label">Children's Books</span><span class="kind-sub">From our portfolio: Mila and the Gentle Dino</span></span></a>
</div>
<div class="philosophy-band v-reveal">
  <div class="philosophy"><div class="eyebrow">Our philosophy</div><blockquote>Every book should still feel unmistakably like the person behind it.</blockquote></div>
  <div class="phil-collage" aria-hidden="true">
    <span class="pc pc-1"><img src="<?php echo esc_url( teebe_site_image( 'cover-6' ) ); ?>" data-asset="cover-6" alt="" decoding="async"></span>
    <span class="pc pc-2"><img src="<?php echo esc_url( teebe_site_image( 'cover-1' ) ); ?>" data-asset="cover-1" alt="" decoding="async"></span>
    <span class="pc pc-3"><img src="<?php echo esc_url( teebe_site_image( 'cover-2' ) ); ?>" data-asset="cover-2" alt="" decoding="async"></span>
    <span class="pc pc-4"><img src="<?php echo esc_url( teebe_site_image( 'cover-5' ) ); ?>" data-asset="cover-5" alt="" decoding="async"></span>
    <span class="pc-logo"><img src="<?php echo esc_url( teebe_site_image( 'logo' ) ); ?>" data-asset="logo" alt=""></span>
  </div>
</div></div></section><section class="v-section tight"><div class="container"><div class="t-grid"><article class="t-card v-reveal"><div class="t-mark" aria-hidden="true">“</div><blockquote class="t-quote">The proofreading gave my manuscript the polish it needed, and the publishing support made the final stage feel clear and manageable. I was genuinely pleased with how everything came together.</blockquote><div class="t-client"><strong>Steve Elliott</strong><span>Author • Proofreading &amp; Publishing</span></div></article><article class="t-card v-reveal" data-delay="1"><div class="t-mark" aria-hidden="true">“</div><blockquote class="t-quote">I felt supported throughout the process. The manuscript was handled with care, the communication was clear, and the finished book felt far more polished and ready for publication.</blockquote><div class="t-client"><strong>Linda</strong><span>Author • Editorial &amp; Publishing Support</span></div></article><article class="t-card v-reveal" data-delay="2"><div class="t-mark" aria-hidden="true">“</div><blockquote class="t-quote">The team helped turn my children's book idea into a finished book I was genuinely proud to publish. The support throughout development was excellent, and seeing the book perform so well on Amazon made the experience even more rewarding.</blockquote><div class="t-client"><strong>Ashley</strong><span>Children's Book Author • Book Development &amp; Publishing</span></div></article><article class="t-card v-reveal" data-delay="3"><div class="t-mark" aria-hidden="true">“</div><blockquote class="t-quote">The illustrations brought the book to life in a way that matched the vision I had from the beginning. Having the same team support the publication process made the whole journey feel much easier and more cohesive.</blockquote><div class="t-client"><strong>Olivia</strong><span>Author • Illustration &amp; Publishing Support</span></div></article></div></div></section><section class="cta-band"><div class="container v-reveal"><h2>Ready to Begin?<span>Tell us about your book</span></h2><p>Where it stands today is the only thing we need to know to start the conversation.</p><div class="actions"><a class="btn btn-gold" href="<?php echo esc_url( home_url( '/book-consultation/' ) ); ?>">Book Your Free Consultation</a></div></div></section>
</section>

<?php
get_footer();
