<?php
/**
 * Portfolio — /portfolio/.
 *
 * Ported from the approved design; hand-maintained from here.
 * wordpress/sync-from-static.py does not generate this file.
 *
 * @package the-ebook-edit
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

get_header();
?>

<section class="site-view" id="portfolio-view">
<section class="page-hero center "><div class="flow-wrap" aria-hidden="true"><div class="flow-line one"></div><div class="flow-line two"></div></div><div class="container" style="position:relative;z-index:1"><div class="v-reveal"><div class="eyebrow">Portfolio</div><h1 class="v-h1" tabindex="-1">Books We're Proud<br>to Have Shaped</h1><p class="v-lead">A selection of books shaped with thoughtful editorial, design and publishing support, each developed around its story, audience and purpose.</p></div></div></section><section class="v-section tight"><div class="container"><div class="pf-open v-reveal" aria-hidden="true"><div class="pf-floor"></div><div class="pf pf-l2"><img src="<?php echo esc_url( teebe_site_image( 'cover-2' ) ); ?>" data-asset="cover-2" alt="Mila and the Gentle Dino book cover" decoding="async" ></div><div class="pf pf-l1"><img src="<?php echo esc_url( teebe_site_image( 'cover-3' ) ); ?>" data-asset="cover-3" alt="The Ghost of Blackthorn Palace book cover" decoding="async" ></div><div class="pf pf-c"><img src="<?php echo esc_url( teebe_site_image( 'cover-4' ) ); ?>" data-asset="cover-4" alt="The Inner Compass book cover" decoding="async" ></div><div class="pf pf-r1"><img src="<?php echo esc_url( teebe_site_image( 'cover-5' ) ); ?>" data-asset="cover-5" alt="Rising Through the Storm book cover" decoding="async" ></div><div class="pf pf-r2"><img src="<?php echo esc_url( teebe_site_image( 'cover-6' ) ); ?>" data-asset="cover-6" alt="The Other Side of Maybe book cover" decoding="async" ></div></div></div></section><section class="v-section tight"><div class="container"><div class="filters" role="group" aria-label="Filter books"><button type="button" data-filter="all" aria-pressed="true">All</button><button type="button" data-filter="childrens" aria-pressed="false">Children's</button><button type="button" data-filter="fiction" aria-pressed="false">Fiction</button><button type="button" data-filter="memoir" aria-pressed="false">Memoir</button><button type="button" data-filter="personal-development" aria-pressed="false">Personal Development</button><button type="button" data-filter="publishing" aria-pressed="false">Publishing</button></div><p id="filterStatus" class="sr-only" aria-live="polite"></p><article class="project" id="pf-from-the-white-house-to-the-outhouse" data-tags="memoir publishing">
      <div class="project-visual v-reveal-cover"><div class="v-stage"><img src="<?php echo esc_url( teebe_site_image( 'cover-1' ) ); ?>" class="v-cover v-cover-tilt" data-asset="cover-1" alt="From the White House to the Outhouse book cover" width="320" decoding="async" ></div></div>
      <div class="project-copy v-reveal"><div class="eyebrow">Editorial &amp; publishing project</div><h2>From the White House<br>to the Outhouse</h2><p class="short">A bold and deeply personal title brought to life with careful editorial attention and a distinctive visual identity. This project reflects our approach to shaping an author's voice into a polished book designed to connect with readers and leave a lasting impression.</p><div class="stat"><div><strong>Editorial</strong>Structure, clarity &amp; polish</div><div><strong>Presentation</strong>Reader ready finish</div><div><strong>Publishing</strong>Platform preparation</div></div><div class="actions"><a class="btn btn-ghost btn-sm" href="<?php echo esc_url( home_url( '/book-consultation/' ) ); ?>">Start Your Book →</a></div></div></article><article class="project flip" id="pf-mila-and-the-gentle-dino" data-tags="childrens publishing">
      <div class="project-visual v-reveal-cover"><div class="v-stage"><img src="<?php echo esc_url( teebe_site_image( 'cover-2' ) ); ?>" class="v-cover v-cover-tilt" data-asset="cover-2" alt="Mila and the Gentle Dino book cover" width="320" decoding="async" ></div></div>
      <div class="project-copy v-reveal"><div class="eyebrow">Children’s fiction</div><h2>Mila and the Gentle Dino</h2><p class="short">Mila and the Gentle Dino is a heartwarming story about an unexpected friendship between a curious young girl and a kind-hearted dinosaur who others are afraid to understand. As Mila spends time with her new friend, she discovers that being different does not mean being frightening, and that kindness begins with listening, understanding, and seeing the world through someone else’s eyes.</p><p class="short">Their friendship introduces children to empathy in a simple way: listening to others, noticing how they feel, including those who seem different, and choosing kindness before making assumptions.</p><p class="book-tagline"><em>A gentle story about friendship, empathy and seeing beyond first impressions.</em></p><div class="stat"><div><strong>Development</strong>Story &amp; presentation</div><div><strong>Illustration</strong>Character-led artwork</div><div><strong>Publishing</strong>Reader ready files</div></div><div class="actions"><a class="btn btn-ghost btn-sm" href="<?php echo esc_url( home_url( '/book-consultation/' ) ); ?>">Start Your Book →</a></div></div></article><article class="project" id="pf-ghost-of-blackthorn-palace" data-tags="fiction publishing">
      <div class="project-visual v-reveal-cover"><div class="v-stage"><img src="<?php echo esc_url( teebe_site_image( 'cover-3' ) ); ?>" class="v-cover v-cover-tilt" data-asset="cover-3" alt="The Ghost of Blackthorn Palace book cover" width="320" decoding="async" ></div></div>
      <div class="project-copy v-reveal"><div class="eyebrow">Gothic fiction</div><h2>The Ghost of Blackthorn Palace</h2><p class="short">The Ghost of Blackthorn Palace follows a young woman drawn to an abandoned estate where locals refuse to set foot after dark. Inside, she begins seeing the ghost of a girl who died in the palace decades ago, but the spirit is not simply haunting the halls. She is trying to reveal what happened to her.</p><p class="short">As buried family secrets surface and the palace grows increasingly hostile, one question becomes impossible to ignore: is the ghost asking for help, or waiting for someone to take her place?</p><p class="book-tagline"><em>Some stories are haunted by ghosts. Others by the truth they refuse to bury.</em></p><div class="stat"><div><strong>Editorial</strong>Pace, tension &amp; voice</div><div><strong>Cover</strong>Atmospheric genre design</div><div><strong>Publishing</strong>Digital &amp; print ready</div></div><div class="actions"><a class="btn btn-ghost btn-sm" href="<?php echo esc_url( home_url( '/book-consultation/' ) ); ?>">Start Your Book →</a></div></div></article><article class="project flip" id="pf-the-inner-compass" data-tags="personal-development publishing">
      <div class="project-visual v-reveal-cover"><div class="v-stage"><img src="<?php echo esc_url( teebe_site_image( 'cover-4' ) ); ?>" class="v-cover v-cover-tilt" data-asset="cover-4" alt="The Inner Compass book cover" width="320" decoding="async" ></div></div>
      <div class="project-copy v-reveal"><div class="eyebrow">Personal development</div><h2>The Inner Compass</h2><p class="short">The Inner Compass is a practical guide for anyone who feels successful on the outside but uncertain about what comes next. Through reflection, mindset shifts, and purposeful action, life coach Sophia Bennett helps readers cut through distraction, rebuild confidence, and make decisions that align with the life they genuinely want to create.</p><p class="book-tagline"><em>Find clarity when success no longer tells you what comes next.</em></p><div class="stat"><div><strong>Writing</strong>Structured non-fiction</div><div><strong>Cover</strong>Calm, confident identity</div><div><strong>Publishing</strong>Platform preparation</div></div><div class="actions"><a class="btn btn-ghost btn-sm" href="<?php echo esc_url( home_url( '/book-consultation/' ) ); ?>">Start Your Book →</a></div></div></article><article class="project" id="pf-rising-through-the-storm" data-tags="memoir publishing">
      <div class="project-visual v-reveal-cover"><div class="v-stage"><img src="<?php echo esc_url( teebe_site_image( 'cover-5' ) ); ?>" class="v-cover v-cover-tilt" data-asset="cover-5" alt="Rising Through the Storm book cover" width="320" decoding="async" ></div></div>
      <div class="project-copy v-reveal"><div class="eyebrow">Memoir / Autobiography</div><h2>Rising Through the Storm</h2><p class="short">Rising Through the Storm is the story of Daniel Mercer, a man shaped by failure, loss, responsibility, and the relentless pressure to keep moving forward. Looking back on the choices that tested him most, he reflects on the moments that changed his direction, the people who influenced his journey, and the lessons that only hardship could teach. It is an honest account of resilience, reinvention, and the belief that even after the hardest seasons, a better chapter can still be written.</p><p class="book-tagline"><em>A story of resilience, reinvention and finding the strength to begin again.</em></p><div class="stat"><div><strong>Editorial</strong>Memoir structure &amp; voice</div><div><strong>Cover</strong>Cinematic portrait design</div><div><strong>Publishing</strong>Digital &amp; print ready</div></div><div class="actions"><a class="btn btn-ghost btn-sm" href="<?php echo esc_url( home_url( '/book-consultation/' ) ); ?>">Start Your Book →</a></div></div></article><article class="project flip" id="pf-the-other-side-of-maybe" data-tags="fiction publishing">
      <div class="project-visual v-reveal-cover"><div class="v-stage"><img src="<?php echo esc_url( teebe_site_image( 'cover-6' ) ); ?>" class="v-cover v-cover-tilt" data-asset="cover-6" alt="The Other Side of Maybe book cover" width="320" decoding="async" ></div></div>
      <div class="project-copy v-reveal"><div class="eyebrow">Contemporary fiction</div><h2>The Other Side of Maybe</h2><p class="short">When a young woman leaves behind the life she knows for a fresh start in an unfamiliar city, she expects distance to make everything simpler. Instead, she finds new friendships, difficult choices, and truths that force her to question the future she thought she wanted. The Other Side of Maybe is a story about courage, belonging, and what can happen when starting over changes more than just your surroundings.</p><p class="book-tagline"><em>Sometimes starting over changes more than where you live.</em></p><div class="stat"><div><strong>Editorial</strong>Character &amp; pacing</div><div><strong>Cover</strong>Warm contemporary design</div><div><strong>Publishing</strong>Reader ready files</div></div><div class="actions"><a class="btn btn-ghost btn-sm" href="<?php echo esc_url( home_url( '/book-consultation/' ) ); ?>">Start Your Book →</a></div></div></article></div></section><section class="cta-band"><div class="container v-reveal"><h2>Your Book Could Be Next<span>Tell us about it</span></h2><p>Whether you have an idea, a draft or a finished manuscript, we can help shape what comes next.</p><div class="actions"><a class="btn btn-gold" href="<?php echo esc_url( home_url( '/book-consultation/' ) ); ?>">Book Your Free Consultation</a></div></div></section>
</section>

<?php
get_footer();
