<?php
/**
 * Editing service page.
 *
 * @package the-ebook-edit
 */

get_header();
?>

<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a> / <a href="<?php echo esc_url( home_url( '/services/' ) ); ?>">Services</a> / Editing</div><p class="eyebrow">Editing</p><h1>Make the manuscript clearer, stronger, and more consistent—without losing its voice.</h1><p class="lead">The right editing level depends on where the manuscript is in its development. We begin by identifying the problems that matter most.</p></div></section>
<section class="section"><div class="container grid-2"><article class="card reveal"><div class="icon-tile">A</div><h2>Editorial assessment</h2><p>A diagnostic review that identifies the manuscript’s strengths, weaknesses, audience fit, and recommended next steps.</p><ul class="service-list"><li>Structure and chapter logic</li><li>Clarity and reader experience</li><li>Voice and positioning</li><li>Priority revision plan</li></ul></article><article class="card reveal"><div class="icon-tile">D</div><h2>Developmental editing</h2><p>Big-picture work on argument, story, sequence, pacing, repetition, gaps, and the overall architecture of the book.</p><ul class="service-list"><li>Chapter-level comments</li><li>Structural recommendations</li><li>Content additions or cuts</li><li>Revision roadmap</li></ul></article><article class="card reveal"><div class="icon-tile">C</div><h2>Line and copy editing</h2><p>Sentence-level refinement for readability, tone, grammar, syntax, word choice, consistency, and flow.</p><ul class="service-list"><li>Tracked changes</li><li>Editorial queries</li><li>Style sheet</li><li>Consistency checks</li></ul></article><article class="card reveal"><div class="icon-tile">P</div><h2>Proofreading</h2><p>A final quality check after layout, focused on remaining errors rather than major rewrites.</p><ul class="service-list"><li>Typos and punctuation</li><li>Formatting consistency</li><li>Headings and navigation</li><li>Final file review</li></ul></article></div></section>
<section class="section section-soft"><div class="container split"><div><p class="eyebrow">A useful distinction</p><h2>Editing is not one single pass.</h2><p class="lead">Structural issues should be solved before sentence polishing, and sentence polishing should be completed before final proofreading.</p><p>Skipping that sequence often means paying to perfect paragraphs that later need to be rewritten or removed.</p></div><div class="feature-panel reveal"><h3>Recommended order</h3><ol><li>Editorial assessment</li><li>Developmental edit</li><li>Author revision</li><li>Line/copy edit</li><li>Formatting</li><li>Proofread</li></ol></div></div></section>
<section class="section"><div class="container"><p class="eyebrow">What you receive</p><h2>Clear edits, clear reasoning, and a manageable revision path.</h2><div class="grid-3 cards"><article class="card"><h3>Marked manuscript</h3><p>Tracked changes and comments that distinguish direct corrections from author decisions.</p></article><article class="card"><h3>Editorial letter</h3><p>A concise explanation of major patterns, priorities, and recommended revision order.</p></article><article class="card"><h3>Style sheet</h3><p>A project reference for spelling, capitalization, terminology, numbers, and recurring choices.</p></article></div></div></section>
<section class="section-tight"><div class="container"><div class="cta-band"><h2>Not sure which edit the manuscript needs?</h2><p>Send a representative sample, approximate word count, genre, and publication goal. We will recommend the most appropriate starting point.</p><a class="button button-gold" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Request an editorial review</a></div></div></section>

<?php
get_footer();
