<?php
/**
 * Process page.
 *
 * @package the-ebook-edit
 */

get_header();
?>

<section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a> / Process</div><p class="eyebrow">Our process</p><h1>A structured path that keeps creative work moving.</h1><p class="lead">Every project is different, but each one benefits from clear stages, decision points, responsibilities, and version control.</p></div></section>
<section class="section"><div class="container"><p class="eyebrow">Step by step</p><h2>Six stages that keep the project on track.</h2><div class="steps"><article class="step"><div><h3>1. Project discovery</h3><p>We discuss your goal, audience, source material, manuscript stage, desired services, timeline, and publishing route.</p><p><strong>Output:</strong> project recommendation and information request.</p></div></article><article class="step"><div><h3>2. Review and scope</h3><p>We review relevant files, identify the real level of work, define deliverables, establish milestones, and confirm what is outside scope.</p><p><strong>Output:</strong> written proposal, timeline, and responsibilities.</p></div></article><article class="step"><div><h3>3. Strategy and planning</h3><p>For writing or developmental projects, we define positioning, outline, chapter goals, voice, source plan, and review cadence.</p><p><strong>Output:</strong> approved project brief and production plan.</p></div></article><article class="step"><div><h3>4. Creation and review</h3><p>Writing or editing proceeds in agreed milestones. Feedback is consolidated so decisions remain clear and revisions stay efficient.</p><p><strong>Output:</strong> milestone drafts and review notes.</p></div></article><article class="step"><div><h3>5. Editorial completion</h3><p>The manuscript moves through the appropriate editing sequence, author review, final text confirmation, and proofreading.</p><p><strong>Output:</strong> approved final manuscript and style record.</p></div></article><article class="step"><div><h3>6. Formatting and publication</h3><p>Final files, navigation, and metadata are prepared for platforms such as Amazon Kindle Direct Publishing (KDP), Apple Books, Kobo Writing Life, Google Play Books, Barnes &amp; Noble Press, and wider distribution through services such as Draft2Digital, then quality checked against a <a href="<?php echo esc_url( home_url( '/publishing/' ) ); ?>">publishing checklist</a>.</p><p><strong>Output:</strong> organized publishing package.</p></div></article></div></div></section>
<section class="section section-blue"><div class="container grid-3"><article class="card"><h3>Clear communication</h3><p>Receive clear updates, decisions and next steps throughout the project.</p></article><article class="card"><h3>Collaborative checkpoints</h3><p>Feedback and approvals are built into each major stage before the work moves forward.</p></article><article class="card"><h3>Organised delivery</h3><p>Final manuscript, formatting files and publishing materials are supplied in a clear, usable package.</p></article></div></section>
<section class="section"><div class="container"><p class="eyebrow">What helps a project succeed</p><h2>A few simple working agreements make a major difference.</h2><div class="grid-2 cards"><article class="card"><h3>From the author or client</h3><ul class="service-list"><li>Timely access to source material</li><li>One consolidated set of feedback</li><li>Clear factual corrections and approvals</li><li>Ownership of permissions and account access</li></ul></article><article class="card"><h3>From The Ebook Edit</h3><ul class="service-list"><li>Clear milestones and deliverables</li><li>Respect for voice and confidentiality</li><li>Transparent queries and recommendations</li><li>Organized files and handoff notes</li></ul></article></div></div></section>
<section class="section-tight"><div class="container"><div class="cta-band"><h2>Start with clarity, not a vague production promise.</h2><p>A short discovery conversation and manuscript review will reveal the right sequence for your project.</p><a class="button button-gold" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Begin project discovery</a></div></div></section>

<?php
get_footer();
