<?php
/**
 * Formatting and publishing support page.
 *
 * @package the-ebook-edit
 */

get_header();
?>

<section class="page-hero"><div class="container"><p class="eyebrow">Formatting and publishing support</p><h1>Prepare clean files and a practical route to publication.</h1><p class="lead">Move from final manuscript to a reader-ready ebook with careful formatting, organized metadata, quality checks, and clear guidance for Amazon Kindle Direct Publishing (KDP), Apple Books, Kobo Writing Life, Google Play Books, Barnes &amp; Noble Press, and wider distribution through services such as Draft2Digital.</p><div class="pill-row"><span class="pill">Amazon KDP</span><span class="pill">Apple Books</span><span class="pill">Kobo Writing Life</span><span class="pill">Google Play Books</span><span class="pill">Barnes &amp; Noble Press</span><span class="pill">Draft2Digital</span></div></div></section>
<section class="section" id="formatting"><div class="container split"><div><p class="eyebrow">Formatting</p><h2>Readable interiors across common ebook formats.</h2><p>Formatting is more than making pages look attractive. It should create hierarchy, navigation, consistency, and a comfortable reading experience across devices and stores, including Kindle, Apple Books, Kobo, and Google Play Books.</p><ul class="service-list"><li>EPUB conversion and cleanup</li><li>Kindle-compatible file preparation</li><li>PDF interior layout</li><li>Clickable table of contents</li><li>Front matter and back matter</li><li>Heading, list, image, and link styling</li><li>File validation and visual checks</li></ul></div><div class="feature-panel reveal"><h3>Typical deliverables</h3><ul class="mini-list"><li><span class="tick">✓</span><span>Final EPUB file</span></li><li><span class="tick">✓</span><span>Kindle-ready file for KDP upload</span></li><li><span class="tick">✓</span><span>Final PDF file where required</span></li><li><span class="tick">✓</span><span>Organized source manuscript</span></li><li><span class="tick">✓</span><span>Upload-ready cover assets supplied by you or your designer</span></li><li><span class="tick">✓</span><span>Final quality checklist</span></li></ul></div></div></section>
<section class="section section-soft"><div class="container"><p class="eyebrow">Publishing support</p><h2>Reduce uncertainty around the final steps.</h2><div class="grid-3 cards"><article class="card"><div class="icon-tile">M</div><h3>Metadata</h3><p>Develop a clear title/subtitle presentation, book description, author bio, keywords, categories, and version notes.</p></article><article class="card"><div class="icon-tile">U</div><h3>Upload preparation</h3><p>Organize files and work through a checklist tailored to platforms such as Amazon KDP, Apple Books, Kobo Writing Life, Google Play Books, Barnes &amp; Noble Press, or Draft2Digital, depending on where you plan to publish.</p></article><article class="card"><div class="icon-tile">Q</div><h3>Quality assurance</h3><p>Review links, navigation, page breaks, images, front matter, back matter, and preview output.</p></article><article class="card"><div class="icon-tile">L</div><h3>Launch materials</h3><p>Prepare the core copy needed for a landing page, email announcement, social posts, and partner outreach.</p></article><article class="card"><div class="icon-tile">V</div><h3>Version control</h3><p>Keep editable source files, final files, edition notes, and update records organized for future revisions.</p></article><article class="card"><div class="icon-tile">G</div><h3>Guided handoff</h3><p>Receive a written summary of files, settings, ownership, and recommended post-launch checks.</p></article></div></div></section>
<section class="section" id="platforms"><div class="container"><p class="eyebrow">Platforms and formats</p><h2>Preparation and guidance for where you plan to publish.</h2><p class="lead">Each platform has its own file, metadata, and cover requirements. We prepare your manuscript and materials so the upload step is straightforward — your account, rights, and publishing decision stay yours.</p><div class="grid-3 cards"><article class="card"><div class="icon-tile">K</div><h3>Amazon Kindle Direct Publishing (KDP)</h3><p>Kindle-compatible formatting, metadata, and an upload checklist prepared for KDP's requirements.</p></article><article class="card"><div class="icon-tile">A</div><h3>Apple Books</h3><p>EPUB formatting and metadata organized for the Apple Books submission process.</p></article><article class="card"><div class="icon-tile">K</div><h3>Kobo Writing Life</h3><p>Clean EPUB files and description copy prepared for Kobo Writing Life.</p></article><article class="card"><div class="icon-tile">G</div><h3>Google Play Books</h3><p>Formatting and metadata prepared to Google Play Books' file standards.</p></article><article class="card"><div class="icon-tile">B</div><h3>Barnes &amp; Noble Press (NOOK)</h3><p>EPUB and metadata prepared for Barnes &amp; Noble Press and the NOOK storefront.</p></article><article class="card"><div class="icon-tile">D</div><h3>Draft2Digital and wider distribution</h3><p>Files organized for aggregators such as Draft2Digital when wider ebook distribution is the goal.</p></article></div></div></section>
<section class="section section-soft"><div class="container"><p class="eyebrow">Good to know</p><h2>Accounts, rights, and expectations stay clear.</h2><div class="faqs"><details><summary>Will The Ebook Edit publish my ebook for me on Kindle or another platform?</summary><p>No. You create and control your own publishing accounts, rights, tax details, and payment information, and you make the final decision to publish. We prepare your files, metadata, and a practical checklist for your chosen platform(s).</p></details><details><summary>Do you guarantee platform approval, sales, or bestseller status?</summary><p>No. We prepare your manuscript and materials to a platform's stated requirements, but approval, sales, and rankings depend on factors outside an editor's control.</p></details><details><summary>Are you affiliated with Amazon, Apple, Kobo, Google, Barnes &amp; Noble, or Draft2Digital?</summary><p>No. The Ebook Edit is an independent editorial and formatting service and is not affiliated with, endorsed by, or officially connected to these companies. All product and platform names are trademarks of their respective owners.</p></details></div></div></section>
<section class="section"><div class="container"><p class="eyebrow">Before publication</p><h2>A final readiness checklist</h2><div class="steps"><article class="step"><div><h3>Editorial sign-off</h3><p>All major revisions are complete and the final text has been proofread.</p></div></article><article class="step"><div><h3>Rights and permissions</h3><p>Quotes, images, data, and third-party material are cleared for use.</p></div></article><article class="step"><div><h3>Metadata approved</h3><p>Title, description, author information, keywords, and categories are consistent.</p></div></article><article class="step"><div><h3>Files tested</h3><p>Navigation, links, layout, images, and readability are checked in relevant previews.</p></div></article><article class="step"><div><h3>Launch ownership clear</h3><p>Accounts, passwords, payment details, files, and responsibilities remain under the author or publisher’s control.</p></div></article></div></div></section>
<section class="section-tight"><div class="container"><div class="cta-band"><h2>Bring the manuscript across the finish line.</h2><p>Share your final draft, intended formats, preferred publishing platform(s), and launch date to plan the publishing stage.</p><a class="button button-gold" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Plan publishing support</a></div></div></section>

<?php
get_footer();
